apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.appName }}"
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: "{{ .Values.appName }}"
      labels:
        app: "{{ .Values.appName }}"
    spec:
      containers:
      - name: "{{ .Values.appName }}"
        image: "{{ .Values.imageName }}"
        imagePullPolicy: Always
        ports:
          - containerPort: {{ .Values.appPort }}
