apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: "{{ .Values.appName }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "tcx-presidio.gen-certs" . ) | indent 2 }}
