apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ .Values.appName }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  nginx.conf: {{ (tpl (.Files.Get "nginx.conf") . ) | b64enc }}
  {{- ( include "tcx-presidio.gen-certs" . ) | indent 2 }}
