apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  type: "{{ .Values.serviceType }}"
  selector:
    app: "{{ .Values.appName }}"
  ports:
    - port: {{ .Values.externalPort }}
      targetPort: {{ .Values.nginxPort }}
      protocol: TCP
      name: "{{ .Values.appName }}"
